### ISSUE TITLE
A Python Module

### ISSUE THREAD

**Issue by shubham9411** [shubham9411/ideas#3]
Lets create a python module.

**Comment by shubham9411** [comment]
#idea 
We can create a module that scrapes data from Google Trend and tell about the trend going viral or how many hits a particular got till the date. That can analyse how much potential in that word. :)

**Comment by shubham9411** [comment]
Just posted this cause it hit my mind... cause no idea is useless. Post yours too. LOL 🔢

**Comment by Yathartha22** [comment]
Seems a good idea. :)
Today while I was downloading a video from YouTube I came across this idea that we can have a module that downloads the video rather than opening a different page(bit tedious). But I found it to be already implemented: [pytube](https://github.com/nficano/pytube), but I thought we can still create our own.

What say !🤔
